"""
Django settings for Inventory project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!v-jbkzvkebbo72-=)510*n4pdhh1a+_ngb*%rz02rs9tojysq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Homepage',
    'GeneralSettings',
    'BusinessPartners',
    'ItemMasterData',
    'Sales',
    'django_select2',
    'Production',
    'Purchasing', 
    'Report',
    'tinymce',
    'PrintDocument',
    'Banking',
    'HR',
    'Financials',
    'Services',
    'QCSM',
]
TINYMCE_DEFAULT_CONFIG = {
    'height': 400,
    'width': 800,
    'plugins': '''
        advlist autolink lists link image charmap print preview hr anchor pagebreak
        searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime
        media nonbreaking save table contextmenu directionality emoticons template paste
        textcolor codesample toc noneditable quickbars
    ''',
    'toolbar': '''
        undo redo | formatselect | bold italic underline strikethrough | forecolor backcolor
        alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | 
        link image media | table | blockquote codesample | charmap emoticons | quickbars
    ''',
    'contextmenu': 'formats | link image',
    'content_css': [
        # Add your own content CSS files here
    ],
    'codesample_languages': [
        { 'text': 'HTML/XML', 'value': 'markup' },
        { 'text': 'JavaScript', 'value': 'javascript' },
        { 'text': 'CSS', 'value': 'css' },
        { 'text': 'Python', 'value': 'python' },
        { 'text': 'Java', 'value': 'java' },
        { 'text': 'Ruby', 'value': 'ruby' },
        { 'text': 'PHP', 'value': 'php' }
        # Add more languages if needed
    ],
    'init_instance_callback': 'tinymce_init_callback'
}


                               
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # ঠিক এইরকম
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
import os
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT=os.path.join(BASE_DIR, 'assets/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
