# Generated by Django 4.2.1 on 2023-08-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('currency_type', models.CharField(choices=[('local', 'Local Currency'), ('foreign', 'Foreign Currency')], default='local', max_length=10)),
                ('vendor_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='GeneralSettings.currency')),
            ],
            options={
                'verbose_name': 'Business Partners | Vendor',
                'verbose_name_plural': 'Business Partners | Vendor',
            },
        ),
    ]
