# Generated by Django 4.2.3 on 2023-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BusinessPartners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesspartner",
            options={
                "verbose_name": "Business Partners",
                "verbose_name_plural": "Business Partners",
            },
        ),
    ]
