# Generated by Django 4.2.3 on 2023-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Company Information",
            },
        ),
    ]
