# Generated by Django 4.2.4 on 2023-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(default=0, max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('website', models.URLField(default='')),
                ('established_year', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
