# Generated by Django 4.2.3 on 2023-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0002_companyinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="established_year",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone_number",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="website",
            field=models.URLField(default=""),
        ),
    ]
