# Generated by Django 4.2.3 on 2023-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "GeneralSettings",
            "0003_companyinfo_email_companyinfo_established_year_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyInfo",
        ),
    ]
