# Generated by Django 4.2.3 on 2023-08-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0005_companyinfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompanyInfo",
            new_name="Company",
        ),
    ]
