# Generated by Django 4.2.4 on 2023-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='reportlogo/'),
        ),
    ]
