# Generated by Django 4.2.1 on 2023-08-29 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_deliveryinfo_address_and_more'),
        ('Production', '0002_alter_production_name_alter_productioncomponent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNumber', models.PositiveIntegerField(default=1, unique=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('PriceTotal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Size', models.CharField(default='', max_length=50)),
                ('Color', models.CharField(default='', max_length=50)),
                ('ProductionNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_receipt_components', to='Production.production')),
                ('ReceiptNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.productionreceipt')),
                ('SalesOrderItem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesorderitem')),
            ],
        ),
    ]
