# Generated by Django 4.2.4 on 2023-08-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0002_remove_item_quantity'),
        ('Production', '0002_remove_billofmaterials_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item'),
        ),
        migrations.AlterField(
            model_name='childcomponent',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item'),
        ),
    ]
