# Generated by Django 4.2.1 on 2023-08-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0001_initial'),
        ('Production', '0003_productionreceipt_productionreceiptitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreceiptitem',
            name='ItemName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item'),
        ),
    ]
