# Generated by Django 4.2.4 on 2023-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_billofmaterials_code_childcomponent_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcomponent',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
