# Generated by Django 4.2.4 on 2023-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_alter_childcomponent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcomponent',
            name='uom',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
