# Generated by Django 4.2.4 on 2023-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_childcomponent_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productioncomponent',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
