# Generated by Django 4.2.3 on 2023-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0010_alter_production_sales_order_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionreceipt",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="productionreceipt",
            old_name="ReceiptNumber",
            new_name="receiptNumber",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="Color",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="PriceTotal",
            new_name="priceTotal",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="Quantity",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="ReceiptNumber",
            new_name="receiptNumber",
        ),
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="Size",
            new_name="size",
        ),
        migrations.RemoveField(
            model_name="productionreceiptitem",
            name="ItemName",
        ),
        migrations.RemoveField(
            model_name="productionreceiptitem",
            name="ProductionNo",
        ),
        migrations.RemoveField(
            model_name="productionreceiptitem",
            name="SalesOrderItem",
        ),
        migrations.AddField(
            model_name="production",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="productioncomponent",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="productionNo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="salesOrderItem",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
