# Generated by Django 4.2.3 on 2023-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0011_rename_created_date_productionreceipt_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Planned"),
                    ("R", "Released"),
                    ("C", "Close"),
                    ("F", "Canceled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
