# Generated by Django 4.2.3 on 2023-08-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0013_rename_sales_order_no_production_salesorder_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionreceiptitem",
            old_name="salesOrderItem",
            new_name="salesOrder",
        ),
    ]
