# Generated by Django 4.2.3 on 2023-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0014_rename_salesorderitem_productionreceiptitem_salesorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionreceiptitem",
            name="po",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="remarks",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="style",
            field=models.CharField(default="", max_length=100),
        ),
    ]
