# Generated by Django 4.2.3 on 2023-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0015_productionreceiptitem_po_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionreceipt",
            name="department",
            field=models.CharField(
                choices=[("1", "N/Z"), ("2", "V/z"), ("3", "ST"), ("4", "BT")],
                default="1",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="department",
            field=models.CharField(default="", max_length=50),
        ),
    ]
