# Generated by Django 4.2.3 on 2023-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0016_productionreceipt_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="priceTotal",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
    ]
