# Generated by Django 4.2.3 on 2023-08-31 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0020_productionreceiptitem_lineno"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionreceiptitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
