# Generated by Django 4.2.4 on 2023-09-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0021_productionreceiptitem_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionreceipt',
            old_name='receiptNumber',
            new_name='docno',
        ),
    ]
