# Generated by Django 4.2.3 on 2023-09-02 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0003_department"),
        ("Production", "0022_rename_receiptnumber_productionreceipt_docno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreceipt",
            name="department",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="GeneralSettings.department",
            ),
        ),
    ]
