# Generated by Django 4.2.3 on 2023-09-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0003_department"),
        ("Production", "0023_alter_productionreceipt_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreceipt",
            name="department",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="GeneralSettings.department",
            ),
        ),
    ]
