# Generated by Django 4.2.3 on 2023-09-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0024_alter_productionreceipt_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="created",
            field=models.DateField(auto_now=True),
        ),
    ]
