# Generated by Django 4.2.3 on 2023-09-03 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0027_alter_productionreceiptitem_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="productioncomponent",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
