# Generated by Django 4.2.3 on 2023-09-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0028_productioncomponent_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="production",
            old_name="created_date",
            new_name="created",
        ),
    ]
