# Generated by Django 4.2.3 on 2023-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0033_productionreceiptitem_orderlineno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionreceiptitem",
            name="po",
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productionreceiptitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
