# Generated by Django 4.2.3 on 2023-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0034_remove_productionreceiptitem_po_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreceiptitem",
            name="department",
            field=models.CharField(default="1", max_length=50),
        ),
    ]
