# Generated by Django 4.2.4 on 2023-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0035_alter_productionreceiptitem_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreceiptitem',
            name='lineNo',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='productionreceiptitem',
            name='orderlineNo',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='productionreceiptitem',
            name='productionNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionreceiptitem',
            name='salesOrder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
