# Generated by Django 4.2.3 on 2023-09-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0046_productioncomponent_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productioncomponent",
            name="price",
        ),
        migrations.RemoveField(
            model_name="productioncomponent",
            name="priceTotal",
        ),
    ]
