# Generated by Django 4.2.3 on 2023-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Production", "0048_remove_billofmaterials_totalamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productioncomponent",
            name="lineNo",
            field=models.CharField(default="0", max_length=4),
        ),
    ]
