# Generated by Django 4.2.4 on 2023-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0049_productioncomponent_lineno'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='uom',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
