# Generated by Django 4.2.4 on 2023-09-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_district_alter_employee_options_policestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.district'),
        ),
        migrations.AddField(
            model_name='employee',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.policestation'),
        ),
    ]
