# Generated by Django 4.2.4 on 2023-09-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_remove_employee_village_delete_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='id_no',
        ),
    ]
