# Generated by Django 4.2.4 on 2023-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_announcement_payroll_leaverequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
