# Generated by Django 4.2.4 on 2023-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_alter_employee_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='id_no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
