# Generated by Django 4.2.4 on 2023-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_payroll_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='id_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='id_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='id_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='id_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
