# Generated by Django 4.2.4 on 2023-09-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_attendance_id_no_document_id_no_employeeskill_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual_leave', 'Casual Leave'), ('medical_leave', 'Medical Leave')], default='casual_leave', max_length=20),
        ),
    ]
