# Generated by Django 4.2.4 on 2023-09-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_leaverequest_leave_duration_leaverequest_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=15)),
                ('id_no', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('trainer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='employee_training_certificates/')),
                ('id_no', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('previous_role', models.CharField(max_length=100)),
                ('new_role', models.CharField(max_length=100)),
                ('salary_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('id_no', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee')),
            ],
        ),
    ]
