# Generated by Django 4.2.4 on 2023-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0019_remove_employee_address_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='intime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='outtime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday')], max_length=10),
        ),
    ]
