# Generated by Django 4.2.4 on 2023-09-24 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0021_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday_marked_as_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='othour',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
