# Generated by Django 4.2.4 on 2023-09-25 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0023_rename_ot_hour_overtimerecord_othour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerecord',
            name='othour',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
