# Generated by Django 4.2.4 on 2023-09-25 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0024_alter_overtimerecord_othour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 25)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='intime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='outtime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
