# Generated by Django 4.2.4 on 2023-09-25 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0027_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lefty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notice_period', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee')),
            ],
            options={
                'verbose_name': 'Lefty',
                'verbose_name_plural': 'Lefties',
            },
        ),
    ]
