# Generated by Django 4.2.4 on 2023-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0028_lefty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lefty',
            name='notice_period',
        ),
    ]
