# Generated by Django 4.2.4 on 2023-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0030_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerecord',
            name='othour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
