# Generated by Django 4.2.4 on 2023-09-15 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sales', '0054_alter_arinvoiceinfo_deliveryno'),
        ('BusinessPartners', '0002_alter_businesspartner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNo', models.PositiveIntegerField(default=1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('totalQty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('customerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartners.businesspartner')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee')),
            ],
            options={
                'verbose_name': 'Outgoing Payement',
                'verbose_name_plural': 'Outgoing Payement',
            },
        ),
        migrations.CreateModel(
            name='IncomingPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNo', models.PositiveIntegerField(default=1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('totalQty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('customerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartners.businesspartner')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee')),
            ],
            options={
                'verbose_name': 'Incoming Payement',
                'verbose_name_plural': 'Incoming Payement',
            },
        ),
    ]
