# Generated by Django 4.2.4 on 2023-09-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0054_alter_arinvoiceinfo_deliveryno'),
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingpaymentinfo',
            options={'verbose_name': 'Incoming Payment', 'verbose_name_plural': 'Incoming Payment'},
        ),
        migrations.AlterModelOptions(
            name='outgoingpaymentinfo',
            options={'verbose_name': 'Outgoing Payment', 'verbose_name_plural': 'Outgoing Payment'},
        ),
        migrations.AlterField(
            model_name='incomingpaymentinfo',
            name='sales_employee',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
        migrations.AlterField(
            model_name='outgoingpaymentinfo',
            name='sales_employee',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
    ]
