# Generated by Django 4.2.4 on 2023-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('description', models.TextField()),
                ('transactions', models.ManyToManyField(to='Financials.transaction')),
            ],
        ),
    ]
