# Generated by Django 4.2.4 on 2023-09-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financials', '0003_journalentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
