# Generated by Django 4.2.4 on 2023-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
