# Generated by Django 4.2.4 on 2023-09-15 12:43

import Homepage.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website', validators=[Homepage.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='introsection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='website'),
        ),
        migrations.AlterField(
            model_name='introsection',
            name='intro_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
