# Generated by Django 4.2.3 on 2023-09-16 02:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("Homepage", "0003_alter_aboutus_image_alter_aboutus_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="text",
            field=tinymce.models.HTMLField(),
        ),
    ]
