# Generated by Django 4.2.3 on 2023-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Purchasing", "0006_apinvoiceinfo_owner_goodsreceiptpoinfo_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptpoinfo",
            name="purchaseOrder",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goodsreceiptpoitem",
            name="purchaseOrder",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
