# Generated by Django 4.2.3 on 2023-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Purchasing", "0008_goodsreceiptpoitem_lineno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="docNo",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
