# Generated by Django 4.2.4 on 2023-09-16 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessPartners', '0002_alter_businesspartner_options'),
        ('Purchasing', '0011_apinvoiceitem_docno_goodsreceiptpoitem_docno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseQuotetionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1)),
                ('docNo', models.PositiveIntegerField(default=1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('totalQty', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('customerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartners.businesspartner')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Quotetion',
                'verbose_name_plural': 'Purchase Quotetion',
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotetionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('priceTotal', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('docNo', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchasequotetioninfo')),
            ],
        ),
    ]
