# Generated by Django 4.2.4 on 2023-09-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0012_purchasequotetioninfo_purchasequotetionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinvoiceinfo',
            name='totalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='apinvoiceitem',
            name='priceTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptpoinfo',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptpoinfo',
            name='totalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptpoitem',
            name='priceTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreturnitem',
            name='priceTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='priceTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderinfo',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderinfo',
            name='totalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotetioninfo',
            name='totalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotetionitem',
            name='priceTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
