# Generated by Django 4.2.4 on 2023-09-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0014_alter_purchasequotetioninfo_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasequotetionitem',
            name='lineNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
