# Generated by Django 4.2.4 on 2023-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0015_purchasequotetionitem_lineno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinvoiceinfo',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreturninfo',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreturninfo',
            name='totalQty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
