# Generated by Django 4.2.1 on 2023-08-29 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GeneralSettings.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDeliveryinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docno', models.PositiveIntegerField(default=1, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Item Delivery',
                'verbose_name_plural': 'Item Delivery',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReceiptinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docno', models.PositiveIntegerField(default=1, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.warehouse')),
            ],
            options={
                'verbose_name': 'Item Received',
                'verbose_name_plural': 'Item Received',
            },
        ),
        migrations.CreateModel(
            name='ItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item')),
                ('item_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.itemreceiptinfo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item')),
                ('item_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.itemdeliveryinfo')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.warehouse'),
        ),
    ]
