# Generated by Django 4.2.1 on 2023-08-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreceipt',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='itemreceiptinfo',
            name='warehouse',
        ),
    ]
