# Generated by Django 4.2.4 on 2023-09-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0003_item_code_alter_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item Master Data', 'verbose_name_plural': 'Item Master Data'},
        ),
        migrations.AlterModelOptions(
            name='itemdeliveryinfo',
            options={'verbose_name': 'Goods Delivery', 'verbose_name_plural': 'Goods Delivery'},
        ),
        migrations.AlterModelOptions(
            name='itemreceiptinfo',
            options={'verbose_name': 'Goods Receipt', 'verbose_name_plural': 'Goods Receipt'},
        ),
    ]
