# Generated by Django 4.2.3 on 2023-09-03 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ItemMasterData",
            "0004_alter_item_options_alter_itemdeliveryinfo_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdelivery",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
