# Generated by Django 4.2.3 on 2023-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0005_itemdelivery_created_itemreceipt_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdelivery",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="itemdelivery",
            name="name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="itemdelivery",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemdelivery",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemdelivery",
            name="uom",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemreceipt",
            name="uom",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="uom",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="itemdelivery",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="itemreceipt",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
