# Generated by Django 4.2.3 on 2023-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0006_itemdelivery_code_itemdelivery_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdeliveryinfo",
            name="totalAmount",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemdeliveryinfo",
            name="totalQty",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemreceiptinfo",
            name="totalAmount",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemreceiptinfo",
            name="totalQty",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
    ]
