# Generated by Django 4.2.3 on 2023-09-04 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0007_itemdeliveryinfo_totalamount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdeliveryinfo",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="itemreceiptinfo",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
