# Generated by Django 4.2.3 on 2023-09-04 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0008_alter_itemdeliveryinfo_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdeliveryinfo",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="itemreceipt",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
