# Generated by Django 4.2.3 on 2023-09-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0009_alter_itemdeliveryinfo_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemdelivery",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemreceipt",
            name="item",
        ),
    ]
