# Generated by Django 4.2.4 on 2023-09-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0013_itemreceipt_department_itemreceiptinfo_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreceipt',
            name='department',
        ),
        migrations.RemoveField(
            model_name='itemreceiptinfo',
            name='department',
        ),
    ]
