# Generated by Django 4.2.4 on 2023-09-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralSettings', '0003_department'),
        ('ItemMasterData', '0014_remove_itemreceipt_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreceipt',
            name='department',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='itemreceiptinfo',
            name='department',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='GeneralSettings.department'),
        ),
    ]
