# Generated by Django 4.2.3 on 2023-09-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ItemMasterData", "0015_itemreceipt_department_itemreceiptinfo_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="size",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
