# Generated by Django 4.2.3 on 2023-09-16 09:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0003_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ItemMasterData", "0017_itemgroup_item_item_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueForProductionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docno", models.PositiveIntegerField(default=1, unique=True)),
                ("created", models.DateField(default=datetime.date.today)),
                (
                    "department",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="GeneralSettings.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": " Issue For Production",
                "verbose_name_plural": "Issue  For  Production",
            },
        ),
        migrations.CreateModel(
            name="IssueForProductionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docNo", models.PositiveIntegerField(default=1)),
                ("lineNo", models.CharField(default="0", max_length=4)),
                ("orderlineNo", models.CharField(default="0", max_length=4)),
                ("salesOrder", models.PositiveIntegerField(default=0)),
                ("productionNo", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(default="", max_length=20, null=True)),
                ("name", models.CharField(default="", max_length=100, null=True)),
                ("uom", models.CharField(default="", max_length=100, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "priceTotal",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=10, null=True
                    ),
                ),
                ("remarks", models.CharField(default="", max_length=100)),
                ("department", models.CharField(default="1", max_length=50)),
                ("created", models.DateField(default=datetime.date.today)),
                (
                    "receiptNumber",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ItemMasterData.issueforproductioninfo",
                    ),
                ),
            ],
        ),
    ]
