# Generated by Django 4.2.3 on 2023-09-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GeneralSettings", "0003_department"),
        ("ItemMasterData", "0018_issueforproductioninfo_issueforproductionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueforproductioninfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="GeneralSettings.department",
            ),
        ),
    ]
