# Generated by Django 4.2.4 on 2023-09-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0020_remove_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
    ]
