# Generated by Django 4.2.4 on 2023-09-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0022_remove_stock_item_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='uom',
        ),
    ]
