# Generated by Django 4.2.4 on 2023-09-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0024_ledgerentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='date',
            new_name='created',
        ),
    ]
