# Generated by Django 4.2.4 on 2023-09-18 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0025_rename_date_ledgerentry_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
