# Generated by Django 4.2.4 on 2023-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0026_stock_created_alter_ledgerentry_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='docNo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='docNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
