# Generated by Django 4.2.4 on 2023-09-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0027_ledgerentry_docno_stock_docno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='instock',
        ),
    ]
