# Generated by Django 4.2.4 on 2023-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0028_remove_ledgerentry_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ITEM_RECEIVED', 'Item Received'), ('ITEM_DELIVERY', 'Item Delivery'), ('ISSUE_FOR_PRODUCTION ', 'ISSUE FOR PRODUCTION'), ('Goods_Receipt_Po_Item ', 'Purchase Goods received')], max_length=100),
        ),
    ]
