# Generated by Django 4.2.4 on 2023-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0029_item_quantity_alter_ledgerentry_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
