# Generated by Django 4.2.4 on 2023-09-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0030_remove_item_quantity_ledgerentry_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='stock',
        ),
    ]
