# Generated by Django 4.2.4 on 2023-08-25 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusinessPartners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.PositiveIntegerField(default=1, unique=True)),
                ('Address', models.CharField(max_length=50)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('CustomerName', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartners.businesspartner')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(max_length=20)),
                ('ItemName', models.CharField(max_length=50)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('PriceTotal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('OrderNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesorderinfo')),
            ],
        ),
    ]
