# Generated by Django 4.2.4 on 2023-08-25 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderinfo',
            name='Created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='ItemCode',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
