# Generated by Django 4.2.4 on 2023-08-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_salesorderinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='ItemCode',
        ),
    ]
