# Generated by Django 4.2.4 on 2023-08-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0002_remove_item_quantity'),
        ('Sales', '0003_remove_salesorderitem_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='ItemName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item'),
        ),
    ]
