# Generated by Django 4.2.1 on 2023-08-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMasterData', '0001_initial'),
        ('Sales', '0003_alter_deliveryinfo_salesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='ItemCode',
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='ItemName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ItemMasterData.item'),
        ),
    ]
