# Generated by Django 4.2.1 on 2023-08-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_remove_deliveryitem_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='salesorderinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
