# Generated by Django 4.2.3 on 2023-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0007_rename_address_deliveryinfo_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="Address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="Created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="CustomerName",
            new_name="customerName",
        ),
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="OrderNumber",
            new_name="orderNumber",
        ),
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="TotalAmount",
            new_name="totalAmount",
        ),
        migrations.RenameField(
            model_name="salesorderitem",
            old_name="OrderNumber",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="salesorderitem",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="salesorderitem",
            old_name="PriceTotal",
            new_name="priceTotal",
        ),
        migrations.RemoveField(
            model_name="deliveryinfo",
            name="salesOrder",
        ),
        migrations.RemoveField(
            model_name="salesorderitem",
            name="ItemName",
        ),
        migrations.RemoveField(
            model_name="salesorderitem",
            name="Quantity",
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="code",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="uom",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
