# Generated by Django 4.2.3 on 2023-08-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0008_rename_address_salesorderinfo_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderinfo",
            name="totalQty",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
    ]
