# Generated by Django 4.2.3 on 2023-08-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0009_salesorderinfo_totalqty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorderinfo",
            old_name="orderNumber",
            new_name="docNo",
        ),
    ]
