# Generated by Django 4.2.3 on 2023-08-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0010_rename_ordernumber_salesorderinfo_docno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesquotetioninfo",
            old_name="docNumber",
            new_name="docNo",
        ),
        migrations.RemoveField(
            model_name="salesquotetionitem",
            name="docNumber",
        ),
        migrations.AddField(
            model_name="salesquotetioninfo",
            name="totalQty",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="order",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Sales.salesquotetioninfo",
            ),
        ),
        migrations.AlterField(
            model_name="salesquotetionitem",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
