# Generated by Django 4.2.3 on 2023-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0011_rename_docnumber_salesquotetioninfo_docno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesquotetionitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesquotetionitem",
            name="priceTotal",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
    ]
