# Generated by Django 4.2.3 on 2023-08-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0014_alter_deliveryinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryitem",
            name="orderNo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="receiptNo",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
