# Generated by Django 4.2.3 on 2023-08-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0015_deliveryitem_orderno_deliveryitem_receiptno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryinfo",
            options={
                "verbose_name": " Delivery",
                "verbose_name_plural": "Delivery Info",
            },
        ),
    ]
