# Generated by Django 4.2.3 on 2023-08-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0017_alter_deliveryitem_orderno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryinfo",
            options={"verbose_name": " Delivery", "verbose_name_plural": "Delivery "},
        ),
    ]
