# Generated by Django 4.2.3 on 2023-09-03 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0019_arinvoiceinfo_arinvoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
