# Generated by Django 4.2.3 on 2023-09-03 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0020_salesorderitem_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="arinvoiceitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
