# Generated by Django 4.2.4 on 2023-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_arinvoiceitem_created_returnitem_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='SalesQuotetion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='salesOrder',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
