# Generated by Django 4.2.3 on 2023-09-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0022_deliveryinfo_salesquotetion_deliveryinfo_salesorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryinfo",
            name="SalesQuotetion",
        ),
        migrations.RemoveField(
            model_name="deliveryinfo",
            name="salesOrder",
        ),
    ]
