# Generated by Django 4.2.4 on 2023-09-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0027_salesorderinfo_sales_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoiceinfo',
            name='sales_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='sales_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
        migrations.AddField(
            model_name='returninfo',
            name='sales_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
        migrations.AddField(
            model_name='salesquotetioninfo',
            name='sales_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.salesemployee'),
        ),
    ]
