# Generated by Django 4.2.4 on 2023-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0030_arinvoiceinfo_owner_deliveryinfo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoiceinfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='returninfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='salesorderinfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='salesquotetioninfo',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Hold'), ('C', 'Close'), ('F', 'Canceled')], default='O', max_length=1),
        ),
    ]
