# Generated by Django 4.2.3 on 2023-09-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0031_arinvoiceinfo_status_deliveryinfo_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="docNo",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
