# Generated by Django 4.2.3 on 2023-09-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0032_salesorderitem_docno"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="lineNo",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
