# Generated by Django 4.2.3 on 2023-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0033_salesorderitem_lineno"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
