# Generated by Django 4.2.3 on 2023-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0034_salesorderitem_color_salesorderitem_ctnno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arinvoiceitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arinvoiceitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arinvoiceitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arinvoiceitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arinvoiceitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arinvoiceitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="color",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="ctnno",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="gweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="nweight",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="size",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salesquotetionitem",
            name="style",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
