# Generated by Django 4.2.4 on 2023-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0035_arinvoiceitem_color_arinvoiceitem_ctnno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='orderlineNo',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
