# Generated by Django 4.2.3 on 2023-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0036_deliveryitem_orderlineno"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryitem",
            name="docNo",
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
