# Generated by Django 4.2.4 on 2023-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0037_deliveryitem_docno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='docNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
