# Generated by Django 4.2.3 on 2023-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0038_alter_deliveryitem_docno"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="color",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="ctnno",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="gweight",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="nweight",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="size",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="style",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
