# Generated by Django 4.2.3 on 2023-09-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0039_salesorderitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderinfo",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="po",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="style",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
