# Generated by Django 4.2.3 on 2023-09-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0040_salesorderinfo_remarks_salesorderitem_po_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderinfo",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
