# Generated by Django 4.2.3 on 2023-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0041_alter_salesorderinfo_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryinfo",
            name="salesOrder",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
