# Generated by Django 4.2.3 on 2023-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0042_deliveryinfo_salesorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinfo",
            name="customerName",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
