# Generated by Django 4.2.4 on 2023-09-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartners', '0002_alter_businesspartner_options'),
        ('Sales', '0043_alter_deliveryinfo_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='customerName',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartners.businesspartner'),
        ),
    ]
