# Generated by Django 4.2.3 on 2023-09-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0044_alter_deliveryinfo_customername"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryinfo",
            name="challanreceiveddate",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="deliveryinfo",
            name="delivertobuyerdate",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
