# Generated by Django 4.2.3 on 2023-09-13 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0047_alter_additionaldeliverydata_delivertobuyerdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionaldeliverydata",
            options={
                "verbose_name": " Buyer Received Challan ",
                "verbose_name_plural": "Buyer Received Challan  ",
            },
        ),
        migrations.AlterField(
            model_name="additionaldeliverydata",
            name="delivery_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Sales.deliveryinfo",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ChallanReceivedDeliveryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challanreceiveddate", models.DateField(default=datetime.date.today)),
                (
                    "delivery_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sales.deliveryinfo",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "  Received Challan From Customer ",
                "verbose_name_plural": "Received Challan From Customer ",
            },
        ),
    ]
