# Generated by Django 4.2.3 on 2023-09-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0050_alter_additionaldeliverydata_delivery_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionaldeliverydata",
            options={
                "verbose_name": " Challan Pass From Gate ",
                "verbose_name_plural": "Challan Pass From Gate ",
            },
        ),
    ]
