# Generated by Django 4.2.4 on 2023-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0051_alter_additionaldeliverydata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoiceinfo',
            name='deliveryNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoiceinfo',
            name='salesOrder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoiceitem',
            name='deliveryNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoiceitem',
            name='deliverylineNo',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='arinvoiceitem',
            name='lineNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoiceitem',
            name='orderNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
