# Generated by Django 4.2.4 on 2023-09-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0052_arinvoiceinfo_deliveryno_arinvoiceinfo_salesorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceitem',
            name='deliverylineNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
