# Generated by Django 4.2.4 on 2023-09-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0053_alter_arinvoiceitem_deliverylineno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceinfo',
            name='deliveryNo',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
