# Generated by Django 4.2.4 on 2023-09-21 03:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0055_customercomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaint',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CustomerComplaintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
                ('code', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('uom', models.CharField(default='', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('solution', models.CharField(default='', max_length=100, null=True)),
                ('symptom', models.CharField(default='', max_length=100, null=True)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.customercomplaint')),
            ],
        ),
    ]
